from .absencereason import AbsenceReasonViewSet
from .attendance import AttendanceViewSet
from .group import GroupViewSet
from .history import HistoryViewSet
from .history import TeacherHistoryViewSet
from .inventory import BookViewSet
from .inventory import InventoryViewSet
from .student import StudentViewSet
from .studentlesson import StudentLessonViewSet
from .subject import SubjectViewSet
from .pending import PendingViewSet
from .plan import PlanViewSet
from .teacher import TeacherViewSet
from .terminal import TerminalViewSet
from .token import TokenViewSet
from .miscellaneous import lang_view
