from rest_framework.serializers import ValidationError  # noqa: F401

from .utils import get_description  # noqa: F401
from .absencereason import AbsenceReasonSerializer
from .attendance import AttendanceSerializer
from .attendance import TookPlaceSrz
from .group import GroupChangeLevelSrz
from .group import GroupChangeTeacherSrz
from .group import GroupCreateSrz
from .group import GroupCompletedSrz
from .group import GroupDetailSerializer
from .group import GroupListSrz
from .group import GroupPendingCreateSerializer
from .group import GroupTrialsSrz
from .group import GroupSellBook
from .group import GroupUpdateSrz
from .group import GroupWithNoLessonSrz
from .group import StudentSubscribeSerializer
from .group import StudentUnsubscribeSerializer
from .history import HistoryListSrz
from .history import TeacherHistoryListSrz
from .inventory import BookListSrz
from .inventory import InventoryListSrz
from .pending import PendingCreateSrz
from .pending import PendingListSrz
from .plan import PlanListSerializer
from .student import AddAdditionalLessonSrz
from .student import AddLessonSrz
from .student import AddLoanLessonSrz
from .student import AddTrialLessonSrz
from .student import CalculateFeeSrz
from .student import StudentBlackSrz
from .student import StudentCreateSerializer
from .student import StudentDetailSerializer
from .student import StudentListSerializer
from .student import StudentOptionsSrz
from .student import StudentPauseSrz
from .student import StudentPendingSerializer
from .student import StudentUpdateSrz
from .student import StudentWhiteSrz
from .student import TransferBalanceSrz
from .studentlesson import StudentLessonAttendanceSrz
from .studentlesson import StudentLessonListSrz
from .subject import SubjectSerializer
from .teacher import TeacherDetailSrz
from .teacher import TeacherFireSrz
from .teacher import TeacherSerializer
from .terminal import TerminalLoginObtainPair
from .terminal import TerminalLoginResponseSerializer
from .terminal import TerminalStudentCheckSerializer
from .terminal import TerminalStudentPayResponseSerializer
from .terminal import TerminalStudentPaySerializer
from .token import TokenObtainPairResponseSerializer
from .token import TokenRefreshResponseSerializer
from .token import TokenRefreshResponseSerializer
