# Generated by Django 4.0.4 on 2022-07-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_group_name_student_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='groups', to='main.student'),
        ),
        migrations.AlterField(
            model_name='group',
            name='days_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Mon-Wed-Fri'), (1, 'Tue-Thu-Sat')], verbose_name='days type'),
        ),
    ]
