# Generated by Django 4.0.4 on 2022-07-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fullname',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='fist name', max_length=45, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='last name', max_length=45, verbose_name='last_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='middle name'),
        ),
    ]
