# Generated by Django 4.0.4 on 2022-07-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_student_fullname_student_first_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pending',
            unique_together={('group', 'student')},
        ),
    ]
