# Generated by Django 4.0.4 on 2022-07-23 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_pending_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendings', to='main.group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='pending',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendings', to='main.student', verbose_name='student'),
        ),
    ]
