# Generated by Django 4.0.4 on 2022-07-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_pending_group_alter_pending_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_student_count',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='maximum number of students'),
            preserve_default=False,
        ),
    ]
