# Generated by Django 4.0.4 on 2022-08-02 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_group_max_student_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.user',),
        ),
    ]
