# Generated by Django 4.0.4 on 2022-08-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220806_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.teacher'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TeacherLesson',
        ),
    ]
