# Generated by Django 4.0.4 on 2022-08-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_lesson_teacher_delete_teacherlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlesson',
            name='has_participated',
            field=models.BooleanField(null=True, verbose_name='has participated'),
        ),
        migrations.AddConstraint(
            model_name='studentlesson',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('has_participated', False), ('has_participated__isnull', True), _connector='OR'), models.Q(('absence_reason__isnull', False)), _connector='OR'), name='absence_reason_null_when_participated'),
        ),
    ]
