# Generated by Django 4.0.4 on 2022-08-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_studentlesson_absence_reason_null_when_participated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlesson',
            name='has_participated',
            field=models.BooleanField(default=False, verbose_name='has participated'),
        ),
    ]
