# Generated by Django 4.0.4 on 2022-08-07 13:29

from django.db import migrations


def delete_student_lessons(apps, _):
    student_lesson_model = apps.get_model('main', 'StudentLesson')

    student_lesson_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_studentlesson_has_participated'),
    ]

    operations = [
        migrations.RunPython(delete_student_lessons),
    ]
