# Generated by Django 4.0.4 on 2022-08-07 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delete_student_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlesson',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.plan'),
            preserve_default=False,
        ),
    ]
