# Generated by Django 4.0.4 on 2022-08-07 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_studentlesson_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('count', models.PositiveSmallIntegerField(verbose_name='count')),
                ('price', main.models.fields.MoneyField(decimal_places=2, max_digits=22, verbose_name='price')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_changed', models.DateTimeField(auto_now=True, verbose_name='last changed')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.branch', verbose_name='branch')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='responsible')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
        ),
    ]
