# Generated by Django 4.0.4 on 2022-08-07 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.book'),
        ),
    ]
