# Generated by Django 4.0.4 on 2022-08-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_group_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'teacher', 'verbose_name_plural': 'teachers'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_fired',
            field=models.BooleanField(default=False, verbose_name='is fired'),
        ),
    ]
