# Generated by Django 4.0.4 on 2022-08-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_teacher_options_user_is_fired'),
    ]

    operations = [
        migrations.RunSQL(
            '''DELETE FROM main_group_students WHERE TRUE;'''
        )
    ]
