# Generated by Django 4.0.4 on 2022-08-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_group_students_add_status_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='students',
        ),
    ]
