# Generated by Django 4.0.4 on 2022-08-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_groupstudent_group_students_groupstudent_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blacklist',
            field=models.BooleanField(default=False, verbose_name='blacklist'),
        ),
    ]
