# Generated by Django 4.0.4 on 2022-08-20 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_student_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.book'),
        ),
    ]
