# Generated by Django 4.0.4 on 2022-08-20 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_group_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='current_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher', verbose_name='current teacher'),
        ),
    ]
