# Generated by Django 4.0.4 on 2022-09-03 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_group_archived_alter_history_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='birth day'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='subjects'),
        ),
    ]
