# Generated by Django 4.0.4 on 2022-09-05 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_student_allow_loan_alter_group_start_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pending',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pending',
            name='level',
            field=models.CharField(default='beginner', max_length=255, verbose_name='level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pending',
            name='start_time',
            field=models.CharField(blank=True, choices=[(8, '8:00 - 9:00'), (9, '9:00 - 10:00'), (10, '10:00 - 11:00'), (11, '11:00 - 12:00'), (12, '12:00 - 13:00'), (13, '13:00 - 14:00'), (14, '14:00 - 15:00'), (15, '15:00 - 16:00'), (16, '16:00 - 17:00'), (17, '17:00 - 18:00'), (18, '18:00 - 19:00'), (19, '19:00 - 20:00'), (20, '20:00 - 21:00')], max_length=5, null=True, verbose_name='start time'),
        ),
        migrations.AddField(
            model_name='pending',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pendings', to='main.subject', verbose_name='group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pending',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='pending',
            unique_together={('subject', 'student')},
        ),
        migrations.RemoveField(
            model_name='pending',
            name='group',
        ),
    ]
