# Generated by Django 4.0.4 on 2022-09-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_pending_unique_together_pending_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='start_time',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(8, '8:00 - 9:00'), (9, '9:00 - 10:00'), (10, '10:00 - 11:00'), (11, '11:00 - 12:00'), (12, '12:00 - 13:00'), (13, '13:00 - 14:00'), (14, '14:00 - 15:00'), (15, '15:00 - 16:00'), (16, '16:00 - 17:00'), (17, '17:00 - 18:00'), (18, '18:00 - 19:00'), (19, '19:00 - 20:00'), (20, '20:00 - 21:00')], null=True, verbose_name='start time'),
        ),
    ]
