# Generated by Django 4.0.4 on 2022-10-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_pending_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='level'),
        ),
    ]
