# Generated by Django 4.0.4 on 2022-11-06 02:53

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_group_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phones',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='phones'),
        ),
    ]
