# Generated by Django 4.0.4 on 2022-11-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_user_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='comment',
            field=models.CharField(default='no comment', max_length=500, verbose_name='comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pending',
            name='days_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Mon-Wed-Fri'), (1, 'Tue-Thu-Sat')], default=0, verbose_name='days type'),
            preserve_default=False,
        ),
    ]
