# Generated by Django 4.0.4 on 2022-11-11 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20221111_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('start_time',), 'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('last_name', 'first_name'), 'permissions': (('manage_students_in_same_branch', 'Manage students in the same branch'),), 'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('days_type', 'start_time', 'current_teacher', 'archived')},
        ),
    ]
