# Generated by Django 4.0.4 on 2022-11-22 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_group_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_set', to='main.subject', verbose_name='subject'),
        ),
    ]
