# Generated by Django 4.0.8 on 2023-01-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_book_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(blank=True, max_length=155, null=True, unique=True, verbose_name='task id')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('started', 'started'), ('success', 'success'), ('failure', 'failure'), ('retry', 'retry'), ('revoked', 'revoked')], max_length=45, verbose_name='status')),
                ('result', models.BinaryField(blank=True, null=True, verbose_name='result')),
                ('date_done', models.DateTimeField(blank=True, null=True, verbose_name='date done')),
                ('traceback', models.TextField(blank=True, null=True, verbose_name='traceback')),
                ('name', models.CharField(blank=True, max_length=155, null=True, verbose_name='name')),
                ('args', models.BinaryField(blank=True, null=True, verbose_name='args')),
                ('kwargs', models.BinaryField(blank=True, null=True, verbose_name='kwargs')),
                ('worker', models.CharField(blank=True, max_length=155, null=True, verbose_name='worker')),
                ('retries', models.IntegerField(blank=True, null=True, verbose_name='retries')),
                ('queue', models.CharField(blank=True, max_length=155, null=True, verbose_name='queue')),
            ],
            options={
                'verbose_name': 'celery task',
                'verbose_name_plural': 'celery tasks',
                'db_table': 'celery_taskmeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CeleryTasksetmeta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('taskset_id', models.CharField(blank=True, max_length=155, null=True, unique=True)),
                ('result', models.BinaryField(blank=True, null=True)),
                ('date_done', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'celery_tasksetmeta',
                'managed': False,
            },
        ),
    ]
