# Generated by Django 4.0.8 on 2023-01-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_celerytask_celerytasksetmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskset',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('taskset_id', models.CharField(blank=True, max_length=155, null=True, unique=True)),
                ('result', models.BinaryField(blank=True, null=True)),
                ('date_done', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'celery_tasksetmeta',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CeleryTasksetmeta',
        ),
    ]
