# Generated by Django 4.0.8 on 2023-01-14 07:24

from django.db import migrations


query_text = '''
update main_studentlesson sl
set lesson_id = actual.l_id
from (select max(id) l_id
      from main_lesson
      group by group_id, completion_timestamp) actual
where lesson_id in (select id
                    from main_lesson
                    except
                    select min(id)
                    from main_lesson
                    group by completion_timestamp, group_id);;

delete from main_lesson
where id in (select id
             from main_lesson
             except
             select min(id)
             from main_lesson
             group by completion_timestamp, group_id);
'''


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_user_is_active'),
    ]

    operations = [
        migrations.RunSQL(query_text),
    ]
