# Generated by Django 4.0.8 on 2023-01-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_lesson_duplicates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='took_place',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('group', 'completion_timestamp')},
        ),
    ]
