# Generated by Django 4.0.8 on 2023-01-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_lesson_took_place_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('group', 'completion_timestamp'), ('teacher', 'completion_timestamp')},
        ),
    ]
