# Generated by Django 4.0.8 on 2023-01-31 17:24

from django.db import migrations
from django.utils.timezone import now


def lesson_set_took_place_null(apps, schema_editor):
    Lesson = apps.get_model('main', 'Lesson')
    lessons = Lesson.objects.filter(
        took_place=False,
        completion_timestamp__gt=now(),
    )
    lessons.update(took_place=None)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.RunPython(lesson_set_took_place_null),
    ]
