# Generated by Django 4.0.8 on 2023-02-02 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_lesson_took_place_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsubscribed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='unsubscribed',
            field=models.ManyToManyField(related_name='past_groups', through='main.Unsubscribed', to='main.student'),
        ),
        migrations.AddField(
            model_name='unsubscribed',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_students', to='main.group'),
        ),
        migrations.AddField(
            model_name='unsubscribed',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.AlterUniqueTogether(
            name='unsubscribed',
            unique_together={('group', 'student')},
        ),
    ]
